# vi: et ts=2 sts=2 ft=ansible
---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: latest # noqa package-latest

- name: Put nginx.conf files
  ansible.builtin.template:
    src: nginx/{{ item }}.j2
    dest: /etc/nginx/{{ item }}
    backup: true
    mode: "0644"
  loop:
    - nginx.conf
    - logformat.conf

- name: Disable default nginx config
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Put http default config
  ansible.builtin.template:
    src: nginx/sites/http_default.conf.j2
    dest: /etc/nginx/sites-available/http_default.conf
    backup: true
    mode: "0644"

- name: Enable http default server
  ansible.builtin.file:
    src: /etc/nginx/sites-available/http_default.conf
    dest: /etc/nginx/sites-enabled/http_default.conf
    state: link

- name: Make default config log directory
  ansible.builtin.file:
    path: /var/log/nginx/default
    state: directory
    owner: www-data
    group: adm
    mode: "0755"

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx.service
    state: reloaded

- name: Install lego
  ansible.builtin.apt:
    name: lego
    state: latest # noqa package-latest

- name: Make data and webroot directories for acme
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /etc/acme/data
    - /etc/acme/webroot

- name: Certify by lego
  ansible.builtin.shell:
    cmd: |
      if [ ! -f /etc/acme/data/certificates/{{ item.apps[0].domain_name }}.crt ]; then
        lego \
          --path /etc/acme/data \
          --accept-tos \
          --http \
          --http.webroot /etc/acme/webroot \
          --email {{ item.acme_email }} \
          --domains {{ item.apps | map(attribute='domain_name') | join(' --domains ') }} \
          run
      fi
  register: certification_out
  changed_when: "'acme: Validations succeeded; requesting certificates' in certification_out.stdout"
  loop: "{{ sites | dict2items | map(attribute='value') }}"

- name: Put systemd service file
  ansible.builtin.template:
    src: "systemd/system/lego.service"
    dest: /etc/systemd/system/{{ item.apps[0].domain_name }}.lego.service
    backup: true
    mode: "0755"
  loop: "{{ sites | dict2items | map(attribute='value') }}"

- name: Put systemd timer file
  ansible.builtin.template:
    src: "systemd/system/lego.timer"
    dest: /etc/systemd/system/{{ item.apps[0].domain_name }}.lego.timer
    backup: true
    mode: "0755"
  loop: "{{ sites | dict2items | map(attribute='value') }}"

- name: Enable lego timer
  ansible.builtin.systemd:
    name: "{{ item.apps[0].domain_name }}.lego.timer"
    state: started
    enabled: true
    daemon_reload: true
  loop: "{{ sites | dict2items | map(attribute='value') }}"
