---
- name: install nginx
  ansible.builtin.apt:
    name: nginx
    state: latest # noqa package-latest

- name: put nginx.conf files
  ansible.builtin.template:
    src: nginx/{{ item }}.j2
    dest: /etc/nginx/{{ item }}
    backup: true
    mode: "0644"
  with_items:
    - nginx.conf
    - logformat.conf
  notify:
    - reload_nginx

- name: disable existing default site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: put default server config
  ansible.builtin.template:
    src: nginx/sites/default_server.conf.j2
    dest: /etc/nginx/sites-available/default_server.conf
    backup: true
    mode: "0644"
  notify:
    - reload_nginx

- name: enable default server
  ansible.builtin.file:
    src: /etc/nginx/sites-available/default_server.conf
    dest: /etc/nginx/sites-enabled/default_server.conf
    state: link
  notify:
    - reload_nginx

- name: put proxy sites config
  ansible.builtin.template:
    src: nginx/sites/proxy.conf.j2
    dest: /etc/nginx/sites-available/{{ item.domain_name }}.conf
    backup: true
    mode: "0644"
  with_items: "{{ sites }}"
  notify:
    - reload_nginx

- name: enable proxy sites
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ item.domain_name }}.conf
    dest: /etc/nginx/sites-enabled/{{ item.domain_name }}.conf
    state: link
  with_items: "{{ sites }}"
  notify:
    - reload_nginx

- name: make log directories
  ansible.builtin.file:
    path: /var/log/nginx/{{ item.domain_name }}
    state: directory
    owner: www-data
    group: adm
    mode: "0755"
  with_items: "{{ sites }}"

- name: make document root directories
  ansible.builtin.file:
    path: "{{ item.document_root.path }}"
    state: directory
    owner: "{{ item.document_root.owner }}"
    group: "{{ item.document_root.group }}"
    mode: "0755"
  with_items: "{{ sites }}"
