sites:
  stg-www.yantene.net:
    user: staging
    acme_email: contact@yantene.net
    directory: /opt/www/stg-www.yantene.net
    apps:
      - domain_name: stg-www.yantene.net
        mode: proxy
        local_port: 4000
      - domain_name: api.stg-www.yantene.net
        mode: proxy
        local_port: 4100
