---
sites:
  - domain_name: yantene.net
    mode: proxy
    target_servers:
      - 127.0.0.1:3000
    document_root:
      path: /opt/www/yantene.net/current/public
      owner: app
      group: app

  - domain_name: api.yantene.net
    mode: proxy
    target_servers:
      - 127.0.0.1:3100
    document_root:
      path: /opt/www/api.yantene.net/current/public
      owner: app
      group: app

  - domain_name: stg.yantene.net
    mode: proxy
    target_servers:
      - 127.0.0.1:4000
    document_root:
      path: /opt/www/stg.yantene.net/current/public
      owner: app
      group: app

  - domain_name: api.stg.yantene.net
    mode: proxy
    target_servers:
      - 127.0.0.1:4100
    document_root:
      path: /opt/www/api.stg.yantene.net/current/public
      owner: app
      group: app
