sites:
  www.yantene.net:
    user: production
    acme_email: contact@yantene.net
    directory: /opt/www/www.yantene.net
    apps:
      - domain_name: www.yantene.net
        mode: proxy
        local_port: 3000
      - domain_name: api.www.yantene.net
        mode: proxy
        local_port: 3100
  stg-www.yantene.net:
    user: staging
    acme_email: contact@yantene.net
    directory: /opt/www/stg-www.yantene.net
    apps:
      - domain_name: stg-www.yantene.net
        mode: proxy
        local_port: 4000
      - domain_name: api.stg-www.yantene.net
        mode: proxy
        local_port: 4100
