name: Setup Node.js and pnpm
description: Setup Node.js and install pnpm dependencies

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        package_json_file: package.json

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: package.json
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Generate type definitions
      shell: bash
      run: pnpm run cf-typegen && pnpm run rr-typegen
