services:
  www.yantene.net:
    build:
      context: .
      dockerfile: ./www.yantene.net/docker/Dockerfile
    ports:
      - target: 3000
        published: "${WWW_YANTENE_NET_PORT:-3000}"
        protocol: tcp
        mode: host
  api.www.yantene.net:
    build:
      context: .
      dockerfile: ./api.www.yantene.net/docker/Dockerfile
    ports:
      - target: 3100
        published: "${API_WWW_YANTENE_NET_PORT:-3100}"
        protocol: tcp
        mode: host
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: api.www.yantene.net
      POSTGRES_USER: api.www.yantene.net
      POSTGRES_PASSWORD: password
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
