# vi: et ts=2 sts=2 ft=ansible
---
- name: Install asdf node plugin
  ansible.builtin.shell:
    cmd: |
      bash -lc "asdf plugin add nodejs || true"
  register: asdf_plugin_add_nodejs_out
  changed_when: "'Plugin named nodejs already added' not in asdf_plugin_add_nodejs_out.stderr"

- name: Install specified version node
  ansible.builtin.shell:
    cmd: |
      bash -lc "asdf install nodejs {{ item }}"
  with_items: "{{ node_versions }}"
  register: asdf_install_nodejs_version_out
  changed_when: "'Installed node-' in asdf_install_nodejs_version_out.stderr"
