# vi: et ts=2 sts=2 ft=ansible
---
- name: Install asdf dependencies
  ansible.builtin.apt:
    name:
      - curl
      - git
    state: latest # noqa package-latest

- name: Install asdf
  ansible.builtin.git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "{{ asdf.root_path }}"
    version: "{{ asdf.version }}"
    clone: true

- name: Put asdf.sh
  ansible.builtin.template:
    src: asdf.sh.j2
    dest: /etc/profile.d/asdf.sh
    mode: "0644"
