# vi: et ts=2 sts=2 ft=ansible
---
- name: Create system group
  ansible.builtin.group:
    name: system

- name: Create system users
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: /bin/bash
    group: system
    groups:
      - wheel
  with_items: "{{ users.system }}"

- name: Set authorized keys to system users
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', './public_keys/{{ item.name }}.pub') }}"
  with_items: "{{ users.system }}"

- name: Create app group
  ansible.builtin.group:
    name: app

- name: Create app users
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: /bin/bash
    group: app
    groups: []
  with_items: "{{ users.app }}"

- name: Set authorized keys to app users
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', './public_keys/{{ item.name }}.pub') }}"
  with_items: "{{ users.app }}"
