---
- name: Default
  hosts: all
  become: true
  roles:
    - set_hostname
    - set_timezone
    - install_utilities
    - setup_docker
    - setup_nginx
    - create_users
    - setup_app
    - setup_compose
