name: ansible

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - infra/ansible/**

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: run ansible-lint
        uses: reviewdog/action-ansiblelint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: true
          ansiblelint_version: 6.8.0
          ansiblelint_flags: infra/ansible
