name: api.yantene.net

on:
  pull_request:
    paths:
      - sites/api.yantene.net/**

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup
        uses: ./.github/workflows/setup_api.yantene.net

      - name: run prettier
        run: npm run lint:prettier
        with:
          workdir: ./sites/api.yantene.net

  prettier-package-json:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup
        uses: ./.github/workflows/setup_api.yantene.net

      - name: run prettier-package-json
        run: npm run lint:prettier-package-json
        with:
          workdir: ./sites/api.yantene.net
