name: api.www.yantene.net

on:
  pull_request:
    paths:
      - api.www.yantene.net/**

jobs:
  jest:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup
        uses: ./.github/workflows/setup

      - name: run jest
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: api.www.yantene.net

  jest-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup
        uses: ./.github/workflows/setup

      - name: run jest for e2e
        run: npm run test:e2e
        working-directory: api.www.yantene.net

  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup
        uses: ./.github/workflows/setup

      - name: run eslint
        uses: reviewdog/action-eslint@v1
        with:
          workdir: api.www.yantene.net
          reporter: github-pr-review
          fail_on_error: true
