name: dev

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup
        uses: ./.github/workflows/setup_dev

      - name: run prettier
        run: npm run lint:prettier

  prettier-package-json:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup
        uses: ./.github/workflows/setup_dev

      - name: run prettier-package-json
        run: npm run lint:prettier-package-json
