name: www.yantene.net

on:
  pull_request:
    paths:
      - www.yantene.net/**

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup
        uses: ./.github/workflows/setup

      - name: run eslint
        uses: reviewdog/action-eslint@v1
        with:
          workdir: www.yantene.net
          reporter: github-pr-review
          fail_on_error: true
